# This rule is not used by the project oauth-dcr-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over oauth.goyongi.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oauth-dcr-controller
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: dcr-admin-role
rules:
- apiGroups:
  - oauth.goyongi.com
  resources:
  - dynamicclientregistrations
  verbs:
  - '*'
- apiGroups:
  - oauth.goyongi.com
  resources:
  - dynamicclientregistrations/status
  verbs:
  - get
